### ISSUE TITLE
[Forslag til begrep] livshendelse

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/begrepskandidater-issue-tracker#1]
**Forslag til term**
livshendelse (nb), livshendning (nn), life event (en)

**Forslag til definisjon**

**Referanser til foreslått definisjon**
Er også brukt i Én digital offentlig sektor. 
https://www.regjeringen.no/no/dokumenter/en-digital-offentlig-sektor/id2653874/?q=livshendelse&ch=3#id0014

**Comment by KjerstiSteien** [comment]
Begrepet er registrert i begrepskatalogen. Lukker saken.
