### ISSUE TITLE
[Forslag til begrep] tjeneste

### ISSUE THREAD

**Issue by hanber** [Informasjonsforvaltning/begrepskandidater-issue-tracker#2]
**Forslag til term**
tjeneste

**Forslag til definisjon**
løsning av en oppgave på bestilling...

gjennomføring av en aktivitet på bestilling...

**Referanser til foreslått definisjon**
Oppgi eventuelle referanser til den foreslåtte definisjonen, eller der begrepet (uten definisjon) er i bruk.

**Kommentar**
Det finnes allerede flere definisjoner i Felles begrepskatalog, hvilket er et argument for at det bør være et fellesbegrep. Begrepet bør være overbegrep for bl.a. elektronisk tjenester, skranketjeneste, fysisk (tjeneste) og må dekke web-løsninger for virksomheter og innbyggere. Jeg opplever at det er essensielt at tjenesten skjer på bestilling fra noen. På den annen side er f.eks. en værvarslingstjeneste et tilbud til alle. Kanskje værvarslingstjenesten egentlig er et tjenestetilbud, og at tjenestene er løsningene av hver enkelt oppgave som blir løst først når en bruker initierer den.

**Comment by KjerstiSteien** [comment]
Tjeneste er definert her https://data.norge.no/concepts/9d406b71-273f-4631-8f3d-52d61943612b
